name: release
run-name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish_release:
    name: Publish Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create ${{ github.ref }} --generate-notes
